### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by Sthefanny** [ChangeFinance/zendesk-flutter-plugin#26]
Just adding the dependency in pubspec.yaml and trying to run, on android I get this:

```
D/FlutterActivityAndFragmentDelegate(27332): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(27332): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine(27332): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@e206664) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate(27332): Attaching FlutterEngine to the Activity that owns this Fragment.
E/CrashlyticsCore(27332): Failed to execute task.
E/CrashlyticsCore(27332): java.util.concurrent.TimeoutException
E/CrashlyticsCore(27332): 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
E/CrashlyticsCore(27332): 	at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
E/CrashlyticsCore(27332): 	at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
E/CrashlyticsCore(27332): 	at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
E/CrashlyticsCore(27332): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
E/CrashlyticsCore(27332): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CrashlyticsCore(27332): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
E/CrashlyticsCore(27332): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
W/Fabric  (27332): Could not call getAdvertisingIdInfo on com.google.android.gms.ads.identifier.AdvertisingIdClient
W/Fabric  (27332): Could not call getId on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
W/Fabric  (27332): Could not call getAdvertisingIdInfo on com.google.android.gms.ads.identifier.AdvertisingIdClient
W/Fabric  (27332): Could not call isLimitAdTrackingEnabled on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
D/NetworkSecurityConfig(27332): No Network Security Config specified, using platform default
I/zygote  (27332): Do partial code cache collection, code=31KB, data=27KB
I/zygote  (27332): After code cache collection, code=31KB, data=27KB
I/zygote  (27332): Increasing code cache capacity to 128KB
I/FA      (27332): Tag Manager is not found and thus will not be used
```

**Comment by sudoFerraz** [comment]
Can you please paste the output of flutter doctor with your pubspec.yml @Sthefanny

**Comment by Sthefanny** [comment]
My Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

My pubspec.yml:

```
name: teste
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zendesk_flutter_plugin: ^1.0.2
  image_picker: ^0.6.5
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
```

And the error, now for a project created from zero, and only with your example code:

```
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/FlutterActivity(20892): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(20892): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(20892): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine(20892): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@4068d38) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate(20892): Attaching FlutterEngine to the Activity that owns this Fragment.
Lost connection to device.
```

**Comment by pascencio** [comment]
Hi @sudoFerraz , I have the same issue with new clean project.

**Comment by pascencio** [comment]
Hi @sudoFerraz,

I have the same issue and found why the application crashes.

https://github.com/ChangeFinance/zendesk-flutter-plugin/blob/master/android/src/main/java/com/getchange/zendesk_flutter_plugin/ZendeskFlutterPlugin.java#L84

I added the dependency and replaced FlutterActivity for FlutterFragmentActivity but didn't work ¿Are there some workarround?

**Comment by onka13** [comment]
I've the same issue too. Any solution yet? 

```
Caused by: java.lang.IllegalArgumentException: FRAGMENT_ACTIVITY_REQUIRED. Add dependency "implementation 'com.android.support:support-v4:28.0.0'" in build.gradle and extend your MainActivity from FlutterFragmentActivity
at com.getchange.zendesk_flutter_plugin.ZendeskFlutterPlugin.registerWith(ZendeskFlutterPlugin.java:84)
```

**Comment by onka13** [comment]
This is how it worked for me.

MainActivity.kt;
```
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
//import io.flutter.app.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine

import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: /*FlutterActivity*/ FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

```

ZendeskFlutterPlugin.java;

Changed the Activity type.
[https://github.com/onka13/zendesk-flutter-plugin/commit/e3d3a34d724011cb20c205e9ba958b0026052099](https://github.com/onka13/zendesk-flutter-plugin/commit/e3d3a34d724011cb20c205e9ba958b0026052099) 

```
//import io.flutter.app.FlutterFragmentActivity;
import io.flutter.embedding.android.FlutterFragmentActivity;
```


pubspec.yaml;
```
  zendesk_flutter_plugin: #^1.0.2
    git:
      url: git://github.com/onka13/zendesk-flutter-plugin
```

**Comment by pascencio** [comment]
> This is how it worked for me.
> 
> MainActivity.kt;
> 
> ```
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.android.FlutterFragmentActivity
> //import io.flutter.app.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> 
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: /*FlutterActivity*/ FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```
> 
> ZendeskFlutterPlugin.java;
> 
> Changed the Activity type.
> [onka13@e3d3a34](https://github.com/onka13/zendesk-flutter-plugin/commit/e3d3a34d724011cb20c205e9ba958b0026052099)
> 
> ```
> //import io.flutter.app.FlutterFragmentActivity;
> import io.flutter.embedding.android.FlutterFragmentActivity;
> ```
> 
> pubspec.yaml;
> 
> ```
>   zendesk_flutter_plugin: #^1.0.2
>     git:
>       url: git://github.com/onka13/zendesk-flutter-plugin
> ```

Thanks @onka13 I will try that!

**Comment by sudoFerraz** [comment]
Thanks @onka13 I will be closing this and if anyone has anything to add I will be glad to open it again

**Comment by sudoFerraz** [comment]
@onka13 Can you please submit a PR with your solution? This is necessary for newer versions of flutter, as currently I was using the v1.9.1+hotfix.6

**Comment by sudoFerraz** [comment]
I would like you to submit the PR with the solution so you can contribute to the code as well, so I will wait for a bit to see if you do it, otherwise I will push it myself, ty 🙏
